
ROOPVELA_VELAGENT_CSOURCES=$(wildcard $(ROOPKOTHA_VELA_HOME)/libs/vela/velagent/vsrc/*.c)
ROOPVELA_VELAGENT_VSOURCE_BASE=$(basename $(notdir $(ROOPVELA_VELAGENT_CSOURCES)))
OBJECTS+=$(addprefix $(ROOPKOTHA_VELA_HOME)$(OBJDIR_COMMON)/, $(addsuffix .o,$(ROOPVELA_VELAGENT_VSOURCE_BASE)))

