
ROOPVELA_VELAROWER_CSOURCES=$(wildcard $(ROOPKOTHA_VELA_HOME)/libs/vela/velarower/vsrc/*.c)
ROOPVELA_VELAROWER_VSOURCE_BASE=$(basename $(notdir $(ROOPVELA_VELAROWER_CSOURCES)))
OBJECTS+=$(addprefix $(ROOPKOTHA_VELA_HOME)$(OBJDIR_COMMON)/, $(addsuffix .o,$(ROOPVELA_VELAROWER_VSOURCE_BASE)))

