
ROOPVELA_CSOURCES=$(wildcard $(ROOPKOTHA_VELA_HOME)/libs/vela/vsrc/*.c)
ROOPVELA_VSOURCE_BASE=$(basename $(notdir $(ROOPVELA_CSOURCES)))
OBJECTS+=$(addprefix $(ROOPKOTHA_VELA_HOME)$(OBJDIR_COMMON)/, $(addsuffix .o,$(ROOPVELA_VSOURCE_BASE)))

