
ROOPVELA_VELAHANDLER_CSOURCES=$(wildcard $(ROOPKOTHA_HOME)/libs/vela/velahandler/vsrc/*.c)
ROOPVELA_VELAHANDLER_VSOURCE_BASE=$(basename $(notdir $(ROOPVELA_VELAHANDLER_CSOURCES)))
OBJECTS+=$(addprefix $(PROJECT_OBJDIR)/, $(addsuffix .o,$(ROOPVELA_VELAHANDLER_VSOURCE_BASE)))

