
ROOPVELA_VELAHANDLER_CSOURCES=$(wildcard $(ROOPKOTHA_VELA_HOME)/libs/vela/velahandler/vsrc/*.c)
ROOPVELA_VELAHANDLER_VSOURCE_BASE=$(basename $(notdir $(ROOPVELA_VELAHANDLER_CSOURCES)))
OBJECTS+=$(addprefix $(ROOPKOTHA_VELA_HOME)$(OBJDIR_COMMON)/, $(addsuffix .o,$(ROOPVELA_VELAHANDLER_VSOURCE_BASE)))

