
ROOPVELA_VELAWIDGET_CSOURCES=$(wildcard $(ROOPKOTHA_VELA_HOME)/libs/vela/velaveil/vsrc/*.c)
ROOPVELA_VELAWIDGET_VSOURCE_BASE=$(basename $(notdir $(ROOPVELA_VELAWIDGET_CSOURCES)))
OBJECTS+=$(addprefix $(ROOPKOTHA_VELA_HOME)$(OBJDIR_COMMON)/, $(addsuffix .o,$(ROOPVELA_VELAWIDGET_VSOURCE_BASE)))

